### ISSUE TITLE
Where to put a button after payment status.

### ISSUE THREAD

**Issue by bennsimon** [bubinimara/PesapalAndroidTest#1]
The code works very well but I would like to know where to add a button and add an action depending on the payment status.

**Comment by bubinimara** [comment]
The example show you how to make a transaction a check it with a webView but you are free to make http requests as you want. For example you can use HttpUrlConnection.

There are two steps, one for make the transaction and one to check the transaction status.
- PostRequest class  create a valid url for make transactions . You need to make an http request with the url generated by this class and follow the redirect to take info about the current transaction like transaction id
- Ipn\* class  create a valid url to check the status of a transaction.
  You can use the url generated by Ipn\* class to make another http request to know the status of the transaction. 

You can find info about the response format of an IPN here :
http://developer.pesapal.com/how-to-integrate/api-reference

**Comment by bennsimon** [comment]
Would you please give me an example of making a http request until the the point of making a button android.I am a new to pesapal integration.

**Comment by bubinimara** [comment]
Hi you can find info to make http request with a button click in this page
http://developer.android.com/training/basics/network-ops/connecting.html

Take the example in the section "Perform Network Operations on a Separate Thread"
and replace the url with one generated by the method getUrl() of the PostRequest class

This is the example on how to generate the  url:
....
PostRequest request = new PostRequest.Builder()  
        .isMobile(true)
        .amount("1000")
        .description("from new libs")
        .mail("lib@mail.com")  
        .name("lib", "newlib")
                .build();
String url = request.getUrl();

The same way for check the transaction detail, only replace PostRequest calss with a Ipn\* class

**Comment by bennsimon** [comment]
Thanks a lot.
